# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('experence', models.IntegerField()),
                ('agent_notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tagent4.Agent'),
        ),
    ]
