# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:20
from __future__ import unicode_literals

import Tagent4.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagent4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=20, validators=[Tagent4.validations.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=20, validators=[Tagent4.validations.validate_last_name]),
        ),
    ]
