# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:25
from __future__ import unicode_literals

import Tagent4.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagent4', '0002_auto_20170907_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, validators=[Tagent4.validations.validate_city]),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=20, validators=[Tagent4.validations.validate_landmark]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=20, validators=[Tagent4.validations.validate_state]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='education',
            field=models.CharField(max_length=50, validators=[Tagent4.validations.validate_education]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialization',
            field=models.CharField(max_length=100, validators=[Tagent4.validations.validate_specelization]),
        ),
    ]
